# Generated by Django 6.1 on 2026-10-07 18:34

#from django.db import migrations


#class Migration(migrations.Migration):

#    dependencies = [
#        ('cfma_base', '0002_actualite_articlestock_competence_elementservice_and_more'),
#    ]

#    operations = [
#    ]


import os
from django.db import migrations

def create_superuser(apps, schema_editor):
    # On récupère le modèle utilisateur personnalisé configuré dans votre projet
    User = apps.get_model('cfma_base', 'User')
    
    # Identifiants par défaut (Modifiables via les variables d'environnement de Render)
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin1')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'cfmaci225.contact@gmail.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'CFMA_1_2026!')

    # On vérifie si l'utilisateur existe déjà pour éviter les doublons au prochain déploiement
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )

class Migration(migrations.Migration):

    dependencies = [
        # ⚠️ VÉRIFIEZ BIEN ICI : Cette ligne doit pointer vers le nom de votre DERNIÈRE migration présente dans le dossier
        ('cfma_base', '0002_initial'), 
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
