"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import re
from pathlib import Path

# ==============================================================================
# 1. IMPORTATION SÉCURISÉE DE CONFIG (DECOUPLE) & CHEMINS
# ==============================================================================
try:
    from decouple import config
except ImportError:
    def config(key, default=None):
        return os.environ.get(key, default)

BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# 2. PARAMÈTRES DE SÉCURITÉ ET CONFIGURATION DE BASE
# ==============================================================================
SECRET_KEY = config('SECRET_KEY')
DEBUG = True  # Mettre à False en production sur Render

# Sécurisation des hôtes pour la production
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.render.com', '*']

AUTH_USER_MODEL = 'cfma_base.User'
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# ==============================================================================
# 3. APPLICATIONS INSTALLÉES
# ==============================================================================
INSTALLED_APPS = [
    "jazzmin",  # Doit être avant django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.sitemaps',   
    
    'cloudinary_storage',  # Stockage Cloudinary
    'django.contrib.staticfiles',
    'cloudinary',
    'cfma_base',
    'storages',
]

SITE_ID = 1

# ==============================================================================
# 4. MIDDLEWARES (AVEC WHITENOISE POUR LES STATIQUES)
# ==============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Gestion des fichiers CSS/JS en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==============================================================================
# 5. CONFIGURATION DE LA BASE DE DONNÉES (SUPABASE POSTGRES)
# ==============================================================================

# Si on est sur Render, on tente d'utiliser la variable DATABASE_URL
if os.environ.get('RENDER'):
    db_url_string = os.environ.get('DATABASE_URL')
else:
    # En local, on utilise directement la chaîne brute depuis decouple/env
    db_url_string = config('DATABASE_URL', default="")

# Nettoyage si la chaîne contient un préfixe accidentel
if db_url_string and db_url_string.startswith("DATABASE_URL="):
    db_url_string = db_url_string.replace("DATABASE_URL=", "", 1)

try:
    # Découpage chirurgical via Regex pour immuniser les caractères spéciaux du mot de passe
    pattern = r"postgresql://([^:]+):(.*)@([^:/]+):(\d+)/(.+)"
    match = re.match(pattern, db_url_string)
    
    if match:
        DB_USER = match.group(1)
        DB_PASSWORD = match.group(2)  # Conserve le mot de passe intact
        DB_HOST = match.group(3)
        DB_PORT = match.group(4)
        DB_NAME = match.group(5)
        
        # SI LE DNS DE VOTRE MAC BUG ET PASSE EN UNKNOWN HOST
        # On force l'IP directe uniquement si on est sur votre machine locale
        if not os.environ.get('RENDER') and DB_HOST == 'db.jzismsfpvubnkzpoxvok.supabase.co':
            DB_HOST = '3.8.214.206'
            
    else:
        raise ValueError("Le format de DATABASE_URL est incorrect ou vide.")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 600,
        }
    }
except Exception as e:
    # Option de secours absolue pour ne pas bloquer votre terminal local si DATABASE_URL échoue
    if not os.environ.get('RENDER'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': 'postgres',
                'USER': 'postgres',
                'PASSWORD': 'VEK?nSG@B6v%dd5',
                'HOST': '3.8.214.206',  # IP Directe
                'PORT': '5432',
                'OPTIONS': {
                    'sslmode': 'require',
                },
                'CONN_MAX_AGE': 600,
            }
        }
    else:
        raise ValueError(f"Erreur critique de configuration de la base sur Render : {e}")

# ==============================================================================
# 6. CONFIGURATION DE L'ENVIRONNEMENT EMAIL & REDIRECTIONS
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '185.107.232.248'  # IP fixe du relais Brevo pour contourner le DNS
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 10

if os.environ.get('RENDER'):
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
else:
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default="")
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default="")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
LOGOUT_REDIRECT_URL = '/'
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.render.com', '*']

# Déclaration UNIQUE de STORAGES (Fichiers médias sur Cloudinary, statiques gérés par Django/WhiteNoise)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# 7. TEMPLATES
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ==============================================================================
# 8. CONFIGURATION INTERFACE JAZZMIN (CHARTE ORANGE)
# ==============================================================================
JAZZMIN_SETTINGS = {
    "site_title": "CFMA Garage Admin",
    "site_header": "CFMA Orange",
    "site_brand": "CFMA Garage",
    "custom_css": "css/custom_admin.css",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Bienvenue sur l'interface de gestion CFMA",
    "copyright": "CFMA Orange Garage",
    "search_model": ["cfma_base.User", "cfma_base.ProfilClient"],
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["cfma_base.view_user"]},
        {"name": "Voir le Site", "url": "/", "new_window": True},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-orange navbar-dark",
    "theme": "default",
    "sidebar": "sidebar-dark-orange",
    "button_classes": {
        "primary": "btn-orange",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

LOGOUT_REDIRECT_URL = '/'
