"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os


import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


AUTH_USER_MODEL = 'cfma_base.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition

INSTALLED_APPS = [
    "jazzmin",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    
    'cloudinary_storage',

    'django.contrib.staticfiles',


    'cloudinary',
    'cfma_base',

]

# config/settings.py

# Détecte automatiquement l'environnement Render
if 'RENDER' in os.environ:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get("cloud_name_cloudinary"),
        'API_KEY': os.environ.get("api_key_cloudinary"),
        'API_SECRET': os.environ.get("api_secret_cloudinary"),
    }
else:
    # Lecture locale via votre fichier .env sur votre Mac
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': config("cloud_name_cloudinary"),
        'API_KEY': config("api_key_cloudinary"),
        'API_SECRET': config("api_secret_cloudinary"),
    }

""" DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
 """
# config/settings.py (Tout en bas, remplacez DEFAULT_FILE_STORAGE par ceci)

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

""" # config/settings.py

# 🎯 1. DICTIONNAIRE DE CONFIGURATION UNIQUE POUR DJANGO
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config("cloud_name_cloudinary"),
    'API_KEY': config("api_key_cloudinary"),
    'API_SECRET': config("api_secret_cloudinary"),
}

# 🎯 2. BRANCHEMENT DU STOCKAGE DES MÉDIAS (REMPLACE LE DISQUE DUR DE RENDER)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
 """




""" 
# Configuration       
cloudinary.config( 
    cloud_name = config("cloud_name_cloudinary"), 
    api_key = config("api_key_cloudinary"), 
    api_secret = config("api_secret_cloudinary"), # Click 'View API Keys' above to copy your API secret
    secure=True
)

# Upload an image
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

upload_result = cloudinary.uploader.upload("https://res.cloudinary.com/demo/image/upload/getting-started/shoes.jpg",
                                           public_id="shoes")
print(upload_result["secure_url"])

# Optimize delivery by resizing and applying auto-format and auto-quality
optimize_url, _ = cloudinary_url("shoes", fetch_format="auto", quality="auto")
print(optimize_url)

# Transform the image: auto-crop to square aspect_ratio
auto_crop_url, _ = cloudinary_url("shoes", width=500, height=500, crop="auto", gravity="auto")
print(auto_crop_url) """



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


# config/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- Vérifiez que cette ligne est bien présente
        'APP_DIRS': True,
        # ...
    },
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'], 

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# config/settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



WSGI_APPLICATION = 'config.wsgi.application'








###jazzmin :

# config/settings.py

JAZZMIN_SETTINGS = {
    # Titre de la page et de l'onglet
    "site_title": "CFMA Garage Admin",
    "site_header": "CFMA Orange",
    "site_brand": "CFMA Garage",

"custom_css": "css/custom_admin.css",

    # 🎯 COULEURS DE LA CHARTE (Classes Bootstrap)
    "site_logo_classes": "img-circle",
    "welcome_sign": "Bienvenue sur l'interface de gestion CFMA",
    "copyright": "CFMA Orange Garage",
    #"search_model": ["auth.User", "cfma_base.ProfilClient"],
    "search_model": ["cfma_base.User", "cfma_base.ProfilClient"],
    
    # Forme des éléments
    
    "topmenu_links": [
        # Modifiez cette ligne dans vos JAZZMIN_SETTINGS :
        {"name": "Accueil", "url": "admin:index", "permissions": ["cfma_base.view_user"]},

        #{"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le Site", "url": "/", "new_window": True},
    ],
}
# 🎯 LE SECRET POUR LA CHARTE ORANGE (UI Tweaks)
JAZZMIN_UI_TWEAKS = {
    # Barre supérieure orange avec texte blanc (navbar-dark)
    "navbar": "navbar-orange navbar-dark",
    
    # Thème général de l'administration (Flatly ou Default)
    "theme": "default",
    
    # Style de la barre latérale (Sidebar) sombre pour faire ressortir l'orange
    "sidebar": "sidebar-dark-orange",
    
    # Couleur des boutons d'action principaux (Enregistrer, etc.) en orange
    "button_classes": {
        "primary": "btn-orange",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}








""" DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
} """


DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL')
    )
}



# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
""" 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'), #BASE_DIR / '',
        'USER' : config('DB_USER'),
        'PASSWORD' : config('DB_PASSWORD'), #'psupuser1*/',
        'HOST' : config('DB_HOST'),
        'PORT' : '5433',
    }
} """


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Ajoutez cette ligne pour lier votre dossier racine
STATICFILES_DIRS = [
    BASE_DIR / "static",
]



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

""" MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
} """



# Emplacement sur le disque dur où les fichiers seront stockés
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Préfixe d'URL pour accéder à ces images dans le navigateur
MEDIA_URL = '/media/'



# =========================================================================
# CONFIGURATIONS EMAILS ET AUTHENTIFICATION
# =========================================================================
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = 'cfma_base.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = 'redirection_portail'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'


# raise InconsistentMigrationHistory(
#     ...
# )
pass


